# Generated by Django 3.1.5 on 2021-01-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('level', models.IntegerField(default=10)),
                ('favorite', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('word', models.CharField(blank=True, max_length=100)),
                ('mean', models.TextField()),
                ('topic', models.CharField(blank=True, default='other', max_length=100)),
                ('level', models.IntegerField(default=10)),
                ('favorite', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
    ]
